version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - php
      - webserver
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=myapp
      - DB_USERNAME=myapp
      - DB_PASSWORD=myapp
    ports:
      - "8080:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:5.7
    container_name: case_mysql_connect
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
    ports:
      - "3306:3306"

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - php
